version: '3.8'

services:
  face_recognition_app:
    image: moamen1358/my_face_recognition_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1